### PR TITLE
drum kit project

### PR DESCRIPTION
**Pull request by Mohit-Aasirwal**
#4

### CODE REVIEW

**Comment by satyampgt4** [comment]
@Mohit-Aasirwal please explain in more detail what you are contributing

**Comment by Mohit-Aasirwal** [comment]
A drum kit project made with DOM manipulation in Javascript and use of basic HTML and CSS.
It can be helpful for other web development enthusiasts to go through the project to understand about Document object modelling and how the webpages can be written using HTML and CSS.

**Comment by satyampgt4** [comment]
files are not visible please add all files and then commit again and push it to GitHub

**Comment by Mohit-Aasirwal** [comment]
> files are not visible please add all files and then commit again and push it to GitHub

Actually I've  pushed the whole folder here!
Kindly consider merging it as if I will add separate files then they will scattered in div subdirectory.

**Comment by satyampgt4** [comment]
> > files are not visible please add all files and then commit again and push it to GitHub
> 
> Actually I've pushed the whole folder here! Kindly consider merging it as if I will add separate files then they will scattered in div subdirectory.

as the files are not visible, we are not able to review it try to make a new pr where all files are visible  


image

**Pull request closed without merging**
